name: Hugo Versioned Build
description: Builds documentation using Hugo
inputs:
  base-url:
    required: false
    description: Optional base url used during build
  working-directory:
    required: false
    description: Path to documentation directory
    default: docs
  hugo-env:
    required: false
    description: Environment variable
    default: production
  keep-master:
    required: false
    description: Preview of the master branch
    default: no
  fetch-from:
    required: false
    description: repo to fetch the versions from
    default: origin

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version-file: ".python-version"
    - name: Install Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
    - name: Setup PYTHONPATH
      shell: bash
      run: |
        PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}/gooddata-pandas/"
        PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}/gooddata-api-client/"
        PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}/gooddata-sdk/"
        echo "PYTHONPATH=$PYTHONPATH" >> $GITHUB_ENV
    - name: Generate Versioned Documentation
      shell: bash
      run: |
        cd docs
        rm -f generate.sh
        wget https://raw.githubusercontent.com/gooddata/gooddata-python-sdk/master/scripts/generate.sh
        chmod +x ./generate.sh
        ./generate.sh ${{ inputs.fetch-from }} master ${{ inputs.keep-master}}
    - name: Hugo Build
      uses: gooddata/gooddata-python-sdk/.github/actions/hugo-build-action@master
      with:
        hugo-env: ${{ inputs.hugo-env }}
        working-directory: ${{ inputs.working-directory }}
        base-url: ${{ inputs.base-url }}
